server:
  port: 9030
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-exam #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iep-permission?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: iep-exam9030
    prefer-ip-address: true
#debug
#logging:
#  level:
#    root: debug