server:
  port: 9030
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-exam #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-8umc2fk3.gz.tencentcdb.com:10020/iep_exam?useUnicode=true&characterEncoding=UTF8&useSSL=false

  jpa:
    database: MySQL
    show-sql: true
  instance:
    instance-id: iep-exam9030
    prefer-ip-address: true
#debug
#logging:
#  level:
#    root: debug