server:
  port: 9030
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-exam #指定服务名
  datasource:
    url: jdbc:mysql://cdb-8umc2fk3.gz.tencentcdb.com:10020/iep_exam?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: qq123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    config:
      allow-override: true
  # rabbitmq:
    ####连接地址
    # host: 127.0.0.1
    ####端口号
    # port: 5672
    ####用户账号
    # username: cuiyijie
    ####用户密码
    # password: cui19960228
    ### 虚拟服务地址
    # virtual-host: /springcloud-virtual-host
eureka:
  instance:
    instance-id: iep-exam9030
    prefer-ip-address: true


#debug
#logging:
#  level:
#    root: debug