

server:
  port: 9050
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-student #指定服务名
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect   
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-8umc2fk3.gz.tencentcdb.com:10020/iep_student?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: qq123456  
    
eureka:
  instance:
    instance-id: iep-student9050
    prefer-ip-address: true
ribbon.ReadTimeout: 120000
ribbon.ConnectTimeout: 30000

#debug
#logging:
#  level:
#    root: debug