server:
  port: 9050
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-student #指定服务名
  jpa:
    database: MySQL
    show-sql: true
eureka:
  instance:
    instance-id: iep-student9050
    prefer-ip-address: true
security:

#debug
#logging:
#  level:
#    root: debug