server:
  port: 10200
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-oss #指定服务名
  jpa:
    database: MySQL
    show-sql: true
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAIoZGQDu9vTi5j
    keysecret: 48xaPufwan7t3o37USEwBMKJfGgmeq
    bucketname1: iep-oss

eureka:
  instance:
    instance-id: iep-oss10200
    prefer-ip-address: true

#debug
#logging:
#  level:
#    root: debug