server:
  port: 8060
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
    #context-path: /api
spring:
  application:
    name: iep-zuul #指定服务名
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    register-with-eureka: false
  instance:
    instance-id: iep-zuul8060
    prefer-ip-address: true
zuul:
  routes:
    teacher:
      serviceId: IEP-TEACHER
      path: /teacher/**
    bbs:
      serviceId: IEP-BBS
      path: /bbs/**
    exam:
      serviceId: IEP-EXAM
      path: /exam/**
    student:
      serviceId: IEP-STUDENT
      path: /student/**
    oss:
      serviceId: IEP-OSS
      path: /oss/**
  ignored-services: "*"
  prefix: "/api"
#debug
#logging:
#  level:
#    root: debug