server:
  port: 8070
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-teacher #指定服务名
  jpa:
    database: MySQL
    show-sql: true
eureka:
  instance:
    instance-id: iep-teacher8070
    prefer-ip-address: true
#debug
#logging:
#  level:
#    root: debug