server:
  port: 8070
  # port: 80 qq登录
  servlet:
    session:
      timeout: 600s
spring:
  application:
    name: iep-teacher #指定服务名
  datasource:
    url: jdbc:mysql://cdb-8umc2fk3.gz.tencentcdb.com:10020/iep_teacher?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: qq123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  instance:
    instance-id: iep-teacher8070
    prefer-ip-address: true
#debug
#logging:
#  level:
#    root: debug