server:
  port: 3344
spring:
  application:
    name: iep-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/guowenzhuang/iep-config.git
          search-paths: /**
          username: 80795289@qq.com
          password: qq123456
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: iep-config3344
    prefer-ip-address: true