server:
  port: 9010
spring:
  application:
    name: iep-bbs #指定服务名
  jpa:
    database: MySQL
    show-sql: true
eureka:
  instance:
    instance-id: iep-bbs9010
    prefer-ip-address: true

#debug
#logging:
#  level:
#    root: debug